### ISSUE TITLE
Add doppins integration and make all dependencies pinned versions

### ISSUE THREAD

**Issue by mackiedrew** [the-heap/Emojions#25] opened 2017-05-02 03:00 UTC
**This is for the snippet section.**
Having hard-set versions for dependencies can allow for better long-term stability. I think we should move to using absolute versions only:
```
  "devDependencies": {
    "husky": "^0.13.3",
    "lint-staged": "^3.4.0",
    "prettier": "^1.2.2"
  }
```
To:
```
  "devDependencies": {
    "husky": "0.13.3",
    "lint-staged": "3.4.0",
    "prettier": "1.2.2"
  }
```

This is probably a bad idea since it makes things extremely manual. However, a service exists that can integrate with GitHub that will manually update and manage dependency upgrades. [Doppins](https://doppins.com/) will give us the flexibility of version ranges but with the stability of pinned versions. 

The workflow would be:

1. The dependency updates
2. Doppins notices we use that dependency
3. Doppins makes a branch on GitHub from the main branch that has only the version number in package.json changed.
4. Doppins creates a pull request for this branch merging into the main branch.
5. This will initiate our code review process (where-ever it happens to be at the time)
6. Our automated testing will install, build, run tests, and vet the update.
7. If everything works we merge the new version in.

This has already saved me twice in three weeks due to some crazy breaking React Updates.

**Comment by teesloane** [comment] 2017-05-02 03:29
This is really interesting @mackiedrew. Let me make sure I understand correctly; as this seems like a good idea (great write up by the way!).

At first, I thought a `yarn.lock` would handle correct package management (I am unsure of it's functionality 100% though — it seems to set explicit verisons?)

So Doppins is looking out for new dependencies automatically? or do we manually trigger it?

This seems like an awesome way to keep your deps up to day.

**Comment by mackiedrew** [comment] 2017-05-02 03:43
You're correct that yarn.lock will lock version numbers! This is fine in almost every case. However, people may not use yarn still. A lot of people may use NPM, which means for the sake of development uniformity it may be nice to have redundancy. It also means we never need to yarn upgrade, and dependency upgrades are never rolled up into another commit/branch.

This is also automatic. All we have to do is review the results of the pull request, then merge!

I understand if it's too much tooling though! :smiley:

**Comment by teesloane** [comment] 2017-05-02 03:53
No... this is really nice. I would like to get some experience with this. This kind of tool sounds really useful especially in keeping people up to date with changing tools — some might say more useful for longer running projects, but regardless, I'm super keen to try it. Thanks for bringing it up!

**Comment by teesloane** [comment] 2017-05-02 03:56
Interesting, running into this:

<img width="777" alt="screenshot 2017-05-01 23 55 15" src="https://cloud.githubusercontent.com/assets/12987958/25603441/bbec4f54-2ec9-11e7-95c5-ae7dbf2f14bd.png">

Doppins might still be syncing with the repo to learn what package manager it uses. will try tomorrow!

**Comment by mackiedrew** [comment] 2017-05-02 04:54
I think I know what the issue is, I think maybe it just looks in the root directory for `requirements.txt` for Python or `package.json` for Node... I think we may not be able to do it .:( Thanks for looking though :)

That's fine though! We don't need it. Maybe I'm wrong though, maybe it will eventually.

**Comment by teesloane** [comment] 2017-05-02 13:26
Ah yes, perhaps the problem is that I'm following a `mono repo` methodology here. Perhaps git sub-modules would work, but I do not know how to use those yet; and am hesistant to split up the sub projects into separate repo's (for the sake of a single source of truth / easier access etc). 

I'm going to close this and  we can reassess / brainstorm in the future. Would have been nice to have.

**Closed as completed by teesloane** 2017-05-02 13:26 UTC
Labels: setup/tooling
